




const Movie = require("../models/Movie");

const seedMovies = async () => {
  try {
    await Movie.deleteMany();

    // Posters via TMDB CDN — no API key needed for direct image URLs
    const BASE = "https://image.tmdb.org/t/p/w500";

    const movies = [

      // ── ENGLISH ────────────────────────────────────────────────────────────
      {
        title: "Inception",
        description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        duration: 148,
        genre: "Sci-Fi",
        language: "English",
        rating: "8.8",
        poster: `${BASE}/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg`,
        releaseDate: new Date("2010-07-16"),
      },
      {
        title: "Interstellar",
        description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        duration: 169,
        genre: "Sci-Fi",
        language: "English",
        rating: "8.6",
        poster: `${BASE}/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg`,
        releaseDate: new Date("2014-11-07"),
      },
      {
        title: "The Dark Knight",
        description: "Batman raises the stakes in his war on crime by partnering with Lt. Gordon and DA Harvey Dent to dismantle organized crime in Gotham.",
        duration: 152,
        genre: "Action",
        language: "English",
        rating: "9.0",
        poster: `${BASE}/qJ2tW6WMUDux911r6m7haRef0WH.jpg`,
        releaseDate: new Date("2008-07-18"),
      },
      {
        title: "Avengers: Endgame",
        description: "After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos's actions and restore balance.",
        duration: 181,
        genre: "Action",
        language: "English",
        rating: "8.4",
        poster: `${BASE}/or06FN3Dka5tukK1e9sl16pB3iy.jpg`,
        releaseDate: new Date("2019-04-26"),
      },
      {
        title: "Oppenheimer",
        description: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
        duration: 180,
        genre: "Drama",
        language: "English",
        rating: "8.4",
        poster: `${BASE}/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg`,
        releaseDate: new Date("2023-07-21"),
      },
      {
        title: "Dune: Part Two",
        description: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
        duration: 166,
        genre: "Sci-Fi",
        language: "English",
        rating: "8.5",
        poster: `${BASE}/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg`,
        releaseDate: new Date("2024-03-01"),
      },
      {
        title: "The Shawshank Redemption",
        description: "Two imprisoned men bond over years, finding solace and eventual redemption through acts of common decency.",
        duration: 142,
        genre: "Drama",
        language: "English",
        rating: "9.3",
        poster: `${BASE}/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg`,
        releaseDate: new Date("1994-09-23"),
      },
      {
        title: "Joker",
        description: "A failed stand-up comedian descends into madness and becomes the iconic supervillain Joker.",
        duration: 122,
        genre: "Thriller",
        language: "English",
        rating: "8.2",
        poster: `${BASE}/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg`,
        releaseDate: new Date("2019-10-04"),
      },
      {
        title: "Mad Max: Fury Road",
        description: "In a post-apocalyptic wasteland, Max joins a rebellious woman fleeing a warlord across the desert.",
        duration: 120,
        genre: "Action",
        language: "English",
        rating: "8.1",
        poster: `${BASE}/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg`,
        releaseDate: new Date("2015-05-15"),
      },
      {
        title: "Parasite",
        description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the rich Park family and the poor Kim clan.",
        duration: 132,
        genre: "Thriller",
        language: "English",
        rating: "8.5",
        poster: `${BASE}/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg`,
        releaseDate: new Date("2019-11-08"),
      },
      {
        title: "Top Gun: Maverick",
        description: "After more than 30 years of service, Pete 'Maverick' Mitchell is called to train a new generation of Top Gun graduates.",
        duration: 131,
        genre: "Action",
        language: "English",
        rating: "8.3",
        poster: `${BASE}/62HCnUTziyWcpDaBO2i1DX17ljH.jpg`,
        releaseDate: new Date("2022-05-27"),
      },
      {
        title: "The Godfather",
        description: "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
        duration: 175,
        genre: "Drama",
        language: "English",
        rating: "9.2",
        poster: `${BASE}/3bhkrj58Vtu7enYsLLeHCm3O60e.jpg`,
        releaseDate: new Date("1972-03-24"),
      },
      {
        title: "Pulp Fiction",
        description: "The lives of two mob hitmen, a boxer, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        duration: 154,
        genre: "Thriller",
        language: "English",
        rating: "8.9",
        poster: `${BASE}/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg`,
        releaseDate: new Date("1994-10-14"),
      },
      {
        title: "Get Out",
        description: "A Black man uncovers disturbing secrets when he meets the family of his white girlfriend.",
        duration: 104,
        genre: "Thriller",
        language: "English",
        rating: "7.7",
        poster: `${BASE}/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg`,
        releaseDate: new Date("2017-02-24"),
      },
      {
        title: "Everything Everywhere All at Once",
        description: "A middle-aged Chinese immigrant is swept into an adventure where she alone can save the world by tapping into the lives of parallel universes.",
        duration: 139,
        genre: "Sci-Fi",
        language: "English",
        rating: "8.0",
        poster: `${BASE}/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg`,
        releaseDate: new Date("2022-04-08"),
      },
      {
        title: "Deadpool & Wolverine",
        description: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but opts for a different path.",
        duration: 128,
        genre: "Action",
        language: "English",
        rating: "7.8",
        poster: `${BASE}/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg`,
        releaseDate: new Date("2024-07-26"),
      },

      // ── HINDI ──────────────────────────────────────────────────────────────
      {
        title: "Kalki 2898 AD",
        description: "A futuristic retelling of the Hindu epic Mahabharata where the final avatar of Vishnu appears in a dystopian world.",
        duration: 180,
        genre: "Sci-Fi",
        language: "Hindi",
        rating: "7.4",
        poster: `${BASE}/ai1cHCQAVNKSHwdDGffBFuQxB89.jpg`,
        releaseDate: new Date("2024-06-27"),
      },
      {
        title: "3 Idiots",
        description: "Two friends embark on a search for a long-lost companion and flashback to their college days filled with rebellion and romance.",
        duration: 170,
        genre: "Comedy",
        language: "Hindi",
        rating: "8.4",
        poster: `${BASE}/66A9MqeTSIejn20RBZnPKDaJHUD.jpg`,
        releaseDate: new Date("2009-12-25"),
      },
      {
        title: "Dangal",
        description: "A retired wrestler trains his daughters to become world-class female wrestlers against all odds.",
        duration: 161,
        genre: "Drama",
        language: "Hindi",
        rating: "8.4",
        poster: `${BASE}/cHd7SnLhL3MmJzDJJmNTz0ZrFkz.jpg`,
        releaseDate: new Date("2016-12-23"),
      },
      {
        title: "PK",
        description: "An alien on Earth loses the device he needs to communicate with his spaceship and takes the help of a journalist.",
        duration: 153,
        genre: "Comedy",
        language: "Hindi",
        rating: "8.1",
        poster: `${BASE}/7YbCTJwjkFxVl4qjEn4LBmxE9Ls.jpg`,
        releaseDate: new Date("2014-12-19"),
      },
      {
        title: "Pathaan",
        description: "An Indian spy takes on the leader of a rogue private army that threatens to attack India.",
        duration: 146,
        genre: "Action",
        language: "Hindi",
        rating: "5.9",
        poster: `${BASE}/uSdT6zU9qBSXHExnXn7dLYiJfPe.jpg`,
        releaseDate: new Date("2023-01-25"),
      },
      {
        title: "Bajrangi Bhaijaan",
        description: "A man with a strong devotion to God helps a mute Pakistani girl lost in India make her way back to her homeland.",
        duration: 163,
        genre: "Drama",
        language: "Hindi",
        rating: "8.0",
        poster: `${BASE}/tXOBdO0fZpgwqo9yCKbFEFSoN1H.jpg`,
        releaseDate: new Date("2015-07-17"),
      },
      {
        title: "Andhadhun",
        description: "A series of unexpected events unfold when a blind pianist accidentally becomes a witness to a murder.",
        duration: 139,
        genre: "Thriller",
        language: "Hindi",
        rating: "8.2",
        poster: `${BASE}/4gMHFxPGOmDAWmGx9PpSLW3xbll.jpg`,
        releaseDate: new Date("2018-10-05"),
      },
      {
        title: "Stree",
        description: "A small town is haunted by the ghost of a woman who abducts men in the night, and only a reluctant group can stop her.",
        duration: 128,
        genre: "Comedy",
        language: "Hindi",
        rating: "7.9",
        poster: `${BASE}/4l7hPnwx7hpH7TiB6qVWoqONHl.jpg`,
        releaseDate: new Date("2018-08-31"),
      },
      {
        title: "Animal",
        description: "A son's complicated relationship with his father descends into violence when his father is attacked.",
        duration: 201,
        genre: "Action",
        language: "Hindi",
        rating: "6.4",
        poster: `${BASE}/kNGnSWoGMPmGMSHxHbRTb4l2HcQ.jpg`,
        releaseDate: new Date("2023-12-01"),
      },
      {
        title: "Zindagi Na Milegi Dobara",
        description: "Three friends take a bachelor trip to Spain and discover themselves and each other along the way.",
        duration: 155,
        genre: "Drama",
        language: "Hindi",
        rating: "8.2",
        poster: `${BASE}/bnNwpHMJKwFKnGBJwMRaMrxjLj5.jpg`,
        releaseDate: new Date("2011-07-15"),
      },
      {
        title: "Dil Chahta Hai",
        description: "Three carefree friends have a falling out after falling for the wrong people in very different ways.",
        duration: 183,
        genre: "Drama",
        language: "Hindi",
        rating: "8.1",
        poster: `${BASE}/kMGNDHY3gEbAUTZBdNXRRGnvWO.jpg`,
        releaseDate: new Date("2001-08-10"),
      },
      {
        title: "Lagaan",
        description: "During the Victorian era, villagers in central India accept a challenge to play cricket against their British rulers to avoid paying taxes.",
        duration: 224,
        genre: "Drama",
        language: "Hindi",
        rating: "8.1",
        poster: `${BASE}/aTBM1ELQY1cSxOxLZFueSYFwcZF.jpg`,
        releaseDate: new Date("2001-06-15"),
      },
      {
        title: "Mirzapur",
        description: "Guns, drugs, and crime dominate the landscape of Purvanchal as rival gangs fight for control of the Mirzapur underworld.",
        duration: 55,
        genre: "Thriller",
        language: "Hindi",
        rating: "8.5",
        poster: `${BASE}/cSWaEaOLApXOC5o7U41lJRQzYBb.jpg`,
        releaseDate: new Date("2018-11-16"),
      },

      // ── TAMIL / TELUGU ─────────────────────────────────────────────────────
      {
        title: "RRR",
        description: "A fictional story about two Indian revolutionaries who embark on a fearless revolt against British colonial rule.",
        duration: 182,
        genre: "Action",
        language: "Tamil",
        rating: "7.8",
        poster: `${BASE}/nEufeZlyAOLqO2brrs0yeF1lgXO.jpg`,
        releaseDate: new Date("2022-03-25"),
      },
      {
        title: "Vikram",
        description: "A special agent investigates a series of murders committed by a masked vigilante group.",
        duration: 174,
        genre: "Action",
        language: "Tamil",
        rating: "8.4",
        poster: `${BASE}/4FqEMvGnGnSG7pZ8hJpVQB1oVYQ.jpg`,
        releaseDate: new Date("2022-06-03"),
      },
      {
        title: "Baahubali: The Beginning",
        description: "In ancient India, a young man searches for his origin and discovers his identity as a lost prince.",
        duration: 159,
        genre: "Action",
        language: "Tamil",
        rating: "8.1",
        poster: `${BASE}/kHBLm3HAa5sSHCMdTqHVhxlm0v1.jpg`,
        releaseDate: new Date("2015-07-10"),
      },
      {
        title: "Pushpa: The Rise",
        description: "A laborer rises through the ranks of a red sandalwood smuggling syndicate in the forests of Andhra Pradesh.",
        duration: 179,
        genre: "Action",
        language: "Tamil",
        rating: "7.6",
        poster: `${BASE}/kJlnHiuUlGxSKlUVBEiMENXUqvN.jpg`,
        releaseDate: new Date("2021-12-17"),
      },
      {
        title: "2.0",
        description: "A robotics scientist and his android creation must battle a deadly supervillain with control over birds.",
        duration: 148,
        genre: "Sci-Fi",
        language: "Tamil",
        rating: "6.6",
        poster: `${BASE}/3SMqRiIeJQqVIjMgSNE4HNpCNbK.jpg`,
        releaseDate: new Date("2018-11-29"),
      },
      {
        title: "Soorarai Pottru",
        description: "Inspired by the life of Captain G.R. Gopinath, the story follows a man who dreams of starting a budget airline.",
        duration: 153,
        genre: "Drama",
        language: "Tamil",
        rating: "8.7",
        poster: `${BASE}/h3QFIoTFBhkJdWAzVEVrwTgbibo.jpg`,
        releaseDate: new Date("2020-11-12"),
      },
      {
        title: "Leo",
        description: "A mild-mannered café owner is forced to confront his dark past when his family is threatened.",
        duration: 164,
        genre: "Action",
        language: "Tamil",
        rating: "7.2",
        poster: `${BASE}/acnfHIeGFAyqYMGNMcLEXJXhRiB.jpg`,
        releaseDate: new Date("2023-10-19"),
      },

      // ── SPANISH ────────────────────────────────────────────────────────────
      {
        title: "Roma",
        description: "A year in the life of a middle-class family in Mexico City in the early 1970s, told through the eyes of their live-in housekeeper.",
        duration: 135,
        genre: "Drama",
        language: "Spanish",
        rating: "7.7",
        poster: `${BASE}/dtPpHiOIozLnRBExHWBOBxfDiCZ.jpg`,
        releaseDate: new Date("2018-11-21"),
      },
      {
        title: "Money Heist",
        description: "A criminal mastermind orchestrates the biggest heist in history by taking hostages inside the Royal Mint of Spain.",
        duration: 70,
        genre: "Thriller",
        language: "Spanish",
        rating: "8.2",
        poster: `${BASE}/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg`,
        releaseDate: new Date("2017-05-02"),
      },
      {
        title: "El Laberinto del Fauno",
        description: "In post-Civil War Spain, a young girl disobeys her stepfather and enters a mysterious labyrinth ruled by a faun.",
        duration: 112,
        genre: "Drama",
        language: "Spanish",
        rating: "8.2",
        poster: `${BASE}/iPHnjNIxnGjSckdyeSOLp9mLYwR.jpg`,
        releaseDate: new Date("2006-10-11"),
      },
      {
        title: "Narcos",
        description: "The true story of the rise and fall of Colombian drug lord Pablo Escobar and the DEA agents who hunted him.",
        duration: 49,
        genre: "Thriller",
        language: "Spanish",
        rating: "8.8",
        poster: `${BASE}/rTmal9fDbwh5F0waol2hq35U4ah.jpg`,
        releaseDate: new Date("2015-08-28"),
      },
      {
        title: "The Platform",
        description: "In a vertical prison where food descends floor by floor, inmates must fight to survive with whatever reaches them.",
        duration: 94,
        genre: "Sci-Fi",
        language: "Spanish",
        rating: "7.0",
        poster: `${BASE}/bkh4BqMnPo2OnqCvKIZAkGtT2Hq.jpg`,
        releaseDate: new Date("2019-11-08"),
      },
      {
        title: "Y Tu Mamá También",
        description: "Two teenage boys and an older woman embark on a road trip across Mexico, exploring sexuality and class divides.",
        duration: 106,
        genre: "Drama",
        language: "Spanish",
        rating: "7.6",
        poster: `${BASE}/nCrNdQHCECfFD9Qeqxr0Ws73sSV.jpg`,
        releaseDate: new Date("2001-06-08"),
      },

      // ── FRENCH ─────────────────────────────────────────────────────────────
      {
        title: "Amélie",
        description: "Amélie is an innocent and naive girl who decides to help those around her after living a sheltered childhood.",
        duration: 122,
        genre: "Comedy",
        language: "French",
        rating: "8.3",
        poster: `${BASE}/jdRPaZC5ARU9mG5tMpAlrBLmLdD.jpg`,
        releaseDate: new Date("2001-04-25"),
      },
      {
        title: "Lupin",
        description: "Inspired by the adventures of Arsène Lupin, gentleman thief Assane Diop seeks to avenge his father's wrongful imprisonment.",
        duration: 45,
        genre: "Thriller",
        language: "French",
        rating: "7.5",
        poster: `${BASE}/sgxOyGkjGgzqGVgI6FGrqmbAJjD.jpg`,
        releaseDate: new Date("2021-01-08"),
      },
      {
        title: "The Intouchables",
        description: "After a paragliding accident leaves a wealthy aristocrat paralyzed, he finds connection with his spirited Senegalese caretaker.",
        duration: 112,
        genre: "Drama",
        language: "French",
        rating: "8.5",
        poster: `${BASE}/1e0KqPXAFBXNHBxGJIRRzmBvpZd.jpg`,
        releaseDate: new Date("2011-11-02"),
      },

      // ── KOREAN ─────────────────────────────────────────────────────────────
      {
        title: "Squid Game",
        description: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games with deadly twists.",
        duration: 60,
        genre: "Thriller",
        language: "Korean",
        rating: "7.9",
        poster: `${BASE}/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg`,
        releaseDate: new Date("2021-09-17"),
      },
      {
        title: "Train to Busan",
        description: "While a zombie virus breaks out in South Korea, passengers on a train from Seoul to Busan fight for their lives.",
        duration: 118,
        genre: "Action",
        language: "Korean",
        rating: "7.6",
        poster: `${BASE}/4tNQFBNRFMEbTj3G7ZEJYJYXlQz.jpg`,
        releaseDate: new Date("2016-07-20"),
      },
      {
        title: "Oldboy",
        description: "A man imprisoned for 15 years without knowing why is suddenly released and seeks his captor.",
        duration: 120,
        genre: "Thriller",
        language: "Korean",
        rating: "8.4",
        poster: `${BASE}/pWb4n9DLbFwIFuG6mRDEz9OwmCv.jpg`,
        releaseDate: new Date("2003-11-21"),
      },

      // ── JAPANESE ───────────────────────────────────────────────────────────
      {
        title: "Spirited Away",
        description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods and spirits.",
        duration: 125,
        genre: "Drama",
        language: "Japanese",
        rating: "9.3",
        poster: `${BASE}/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg`,
        releaseDate: new Date("2003-03-28"),
      },
      {
        title: "Your Name",
        description: "Two teenagers share a profound, magical connection by inexplicably swapping bodies with each other.",
        duration: 106,
        genre: "Drama",
        language: "Japanese",
        rating: "8.4",
        poster: `${BASE}/q719jXXEzOoYaps6babgKnONONX.jpg`,
        releaseDate: new Date("2016-09-07"),
      },
      {
        title: "Akira",
        description: "A secret military project threatens to destabilize the post-apocalyptic city of Neo-Tokyo when it falls into the hands of a teenager.",
        duration: 124,
        genre: "Sci-Fi",
        language: "Japanese",
        rating: "8.0",
        poster: `${BASE}/7Wh5EkwNNBZd77Gm7ysTMNOLzPW.jpg`,
        releaseDate: new Date("1988-07-16"),
      },

      // ── ITALIAN ────────────────────────────────────────────────────────────
      {
        title: "Life Is Beautiful",
        description: "A Jewish man uses humor and imagination to shield his son from the horrors of a Nazi concentration camp.",
        duration: 116,
        genre: "Drama",
        language: "Italian",
        rating: "8.6",
        poster: `${BASE}/mfnkSeeZByIHT0Ou9ylv9o7Qlca.jpg`,
        releaseDate: new Date("1997-10-22"),
      },

      // ── GERMAN ─────────────────────────────────────────────────────────────
      {
        title: "Dark",
        description: "A family saga with a supernatural twist — time travel — set across four generations in a German town.",
        duration: 60,
        genre: "Sci-Fi",
        language: "German",
        rating: "8.8",
        poster: `${BASE}/apbrbWs5aAezSlxhZPSFIlLVgCl.jpg`,
        releaseDate: new Date("2017-12-01"),
      },

      // ── PORTUGUESE ─────────────────────────────────────────────────────────
      {
        title: "City of God",
        description: "The fight of two young men in the slums of Rio de Janeiro — one wants to become a photographer, the other a gangster.",
        duration: 130,
        genre: "Thriller",
        language: "Portuguese",
        rating: "8.6",
        poster: `${BASE}/k7eYdWvhYQyRQoU2TB2A2Xu2grZ.jpg`,
        releaseDate: new Date("2003-01-17"),
      },
      {
        title: "Elite",
        description: "When three working-class teens enroll in an exclusive private school, tensions arise among the privileged students.",
        duration: 45,
        genre: "Thriller",
        language: "Spanish",
        rating: "7.4",
        poster: `${BASE}/3NTAbAiao4JLzFQw6YxP1YZppM8.jpg`,
        releaseDate: new Date("2018-10-05"),
      },

      // ── EXTRA ENGLISH (fill up to 60) ────────────────────────────────────
      {
        title: "John Wick",
        description: "An ex-hitman comes out of retirement to track down the gangsters that killed his dog and stole his car.",
        duration: 101,
        genre: "Action",
        language: "English",
        rating: "7.4",
        poster: `${BASE}/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg`,
        releaseDate: new Date("2014-10-24"),
      },
      {
        title: "Knives Out",
        description: "A detective investigates the death of a crime novelist at his estate after his entire family becomes suspects.",
        duration: 130,
        genre: "Comedy",
        language: "English",
        rating: "7.9",
        poster: `${BASE}/pThyQovXQrws2Y4CA5tF23cMmyQ.jpg`,
        releaseDate: new Date("2019-11-27"),
      },
      {
        title: "Tenet",
        description: "Armed with only one word, a secret agent journeys through a twilight world of international espionage using time inversion.",
        duration: 150,
        genre: "Sci-Fi",
        language: "English",
        rating: "7.4",
        poster: `${BASE}/k68nPLbIST6NP96JmTxmZijZTaa.jpg`,
        releaseDate: new Date("2020-08-26"),
      },
      {
        title: "The Menu",
        description: "A young couple travels to a remote island to eat at an exclusive restaurant where the chef has prepared a meal with shocking revelations.",
        duration: 107,
        genre: "Thriller",
        language: "English",
        rating: "7.2",
        poster: `${BASE}/v7UF7ypAqjsFZFdjksjQ7IUpXdn.jpg`,
        releaseDate: new Date("2022-11-18"),
      },
      {
        title: "Hereditary",
        description: "When the matriarch of the Graham family passes away, her daughter's family begins to unravel cryptic and terrifying secrets.",
        duration: 127,
        genre: "Thriller",
        language: "English",
        rating: "7.3",
        poster: `${BASE}/4GDy4HKGP1oSHAO9gfTXouiOQyM.jpg`,
        releaseDate: new Date("2018-06-08"),
      },
      {
        title: "No Country for Old Men",
        description: "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and finds $2 million in cash.",
        duration: 122,
        genre: "Thriller",
        language: "English",
        rating: "8.1",
        poster: `${BASE}/6d5XCtnSWYDJzBV2FkJEUOABR4x.jpg`,
        releaseDate: new Date("2007-11-09"),
      },
    ];

    await Movie.insertMany(movies);
    console.log(`✅ ${movies.length} real movies seeded successfully`);
  } catch (error) {
    console.error("❌ Error seeding movies:", error);
  }
};

module.exports = seedMovies;